-- Analytics Container Database Seed
-- This seed file creates sample data for testing analytics jobs
-- SQLite compatible version

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    last_login TEXT,
    status TEXT DEFAULT 'active',
    user_type TEXT DEFAULT 'regular',
    country TEXT,
    age INTEGER,
    subscription_plan TEXT DEFAULT 'free'
);

-- Sessions table
CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES users(id),
    session_token TEXT UNIQUE NOT NULL,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    ip_address TEXT,
    user_agent TEXT,
    duration_seconds INTEGER,
    pages_visited INTEGER DEFAULT 1,
    device_type TEXT,
    browser TEXT
);

-- Events table
CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES users(id),
    session_id INTEGER REFERENCES sessions(id),
    event_type TEXT NOT NULL,
    event_data TEXT, -- JSON as TEXT in SQLite
    created_at TEXT DEFAULT (datetime('now')),
    page_url TEXT,
    referrer TEXT
);

-- Products table
CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    category TEXT,
    price REAL,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now')),
    status TEXT DEFAULT 'active'
);

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER REFERENCES users(id),
    product_id INTEGER REFERENCES products(id),
    quantity INTEGER DEFAULT 1,
    total_amount REAL,
    status TEXT DEFAULT 'pending',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

-- Insert sample users (100 users for faster seeding)
INSERT INTO users (name, email, created_at, updated_at, last_login, status, user_type, country, age, subscription_plan)
VALUES 
    ('John Doe', 'john@example.com', datetime('now', '-365 days'), datetime('now', '-30 days'), datetime('now', '-7 days'), 'active', 'premium', 'USA', 25, 'premium'),
    ('Jane Smith', 'jane@example.com', datetime('now', '-300 days'), datetime('now', '-25 days'), datetime('now', '-5 days'), 'active', 'pro', 'Canada', 30, 'basic'),
    ('Bob Johnson', 'bob@example.com', datetime('now', '-200 days'), datetime('now', '-20 days'), datetime('now', '-3 days'), 'active', 'regular', 'UK', 28, 'free'),
    ('Alice Brown', 'alice@example.com', datetime('now', '-150 days'), datetime('now', '-15 days'), datetime('now', '-1 days'), 'active', 'premium', 'Germany', 35, 'premium'),
    ('Charlie Wilson', 'charlie@example.com', datetime('now', '-100 days'), datetime('now', '-10 days'), datetime('now', '-2 days'), 'active', 'pro', 'France', 22, 'basic');

-- Insert more users using a simple loop approach
INSERT INTO users (name, email, created_at, updated_at, last_login, status, user_type, country, age, subscription_plan)
SELECT 
    'User ' || (row_number() OVER ()) + 5,
    'user' || (row_number() OVER ()) + 5 || '@example.com',
    datetime('now', '-' || (abs(random()) % 365) || ' days'),
    datetime('now', '-' || (abs(random()) % 30) || ' days'),
    CASE 
        WHEN abs(random()) % 10 > 3 THEN datetime('now', '-' || (abs(random()) % 30) || ' days')
        ELSE NULL
    END,
    CASE 
        WHEN abs(random()) % 10 > 1 THEN 'active'
        ELSE 'inactive'
    END,
    CASE 
        WHEN abs(random()) % 10 > 8 THEN 'premium'
        WHEN abs(random()) % 10 > 6 THEN 'pro'
        ELSE 'regular'
    END,
    CASE 
        WHEN abs(random()) % 10 > 7 THEN 'USA'
        WHEN abs(random()) % 10 > 5 THEN 'Canada'
        WHEN abs(random()) % 10 > 3 THEN 'UK'
        WHEN abs(random()) % 10 > 1 THEN 'Germany'
        ELSE 'France'
    END,
    (abs(random()) % 50) + 18,
    CASE 
        WHEN abs(random()) % 10 > 7 THEN 'free'
        WHEN abs(random()) % 10 > 4 THEN 'basic'
        WHEN abs(random()) % 10 > 2 THEN 'premium'
        ELSE 'enterprise'
    END
FROM (
    SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
    SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
    SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
    SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
    SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
    SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
    SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
    SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION
    SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION
    SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION
    SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION
    SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION
    SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION
    SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90 UNION
    SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95
);

-- Insert sample products (20 products)
INSERT INTO products (name, category, price, created_at, updated_at, status)
VALUES 
    ('Laptop Pro', 'Electronics', 1299.99, datetime('now', '-180 days'), datetime('now', '-30 days'), 'active'),
    ('Running Shoes', 'Sports', 89.99, datetime('now', '-150 days'), datetime('now', '-25 days'), 'active'),
    ('Coffee Maker', 'Home & Garden', 79.99, datetime('now', '-120 days'), datetime('now', '-20 days'), 'active'),
    ('Programming Book', 'Books', 49.99, datetime('now', '-100 days'), datetime('now', '-15 days'), 'active'),
    ('Wireless Headphones', 'Electronics', 199.99, datetime('now', '-90 days'), datetime('now', '-10 days'), 'active'),
    ('Yoga Mat', 'Sports', 29.99, datetime('now', '-80 days'), datetime('now', '-8 days'), 'active'),
    ('Desk Lamp', 'Home & Garden', 45.99, datetime('now', '-70 days'), datetime('now', '-5 days'), 'active'),
    ('Cookbook', 'Books', 24.99, datetime('now', '-60 days'), datetime('now', '-3 days'), 'active'),
    ('Smartphone', 'Electronics', 699.99, datetime('now', '-50 days'), datetime('now', '-2 days'), 'active'),
    ('Tennis Racket', 'Sports', 149.99, datetime('now', '-40 days'), datetime('now', '-1 days'), 'active'),
    ('Garden Tools', 'Home & Garden', 59.99, datetime('now', '-35 days'), datetime('now', '-1 days'), 'active'),
    ('Novel', 'Books', 14.99, datetime('now', '-30 days'), datetime('now', '-1 days'), 'active'),
    ('Tablet', 'Electronics', 399.99, datetime('now', '-25 days'), datetime('now', '-1 days'), 'active'),
    ('Basketball', 'Sports', 19.99, datetime('now', '-20 days'), datetime('now', '-1 days'), 'active'),
    ('Vacuum Cleaner', 'Home & Garden', 199.99, datetime('now', '-15 days'), datetime('now', '-1 days'), 'active'),
    ('Textbook', 'Books', 89.99, datetime('now', '-10 days'), datetime('now', '-1 days'), 'active'),
    ('Camera', 'Electronics', 599.99, datetime('now', '-8 days'), datetime('now', '-1 days'), 'active'),
    ('Soccer Ball', 'Sports', 24.99, datetime('now', '-5 days'), datetime('now', '-1 days'), 'active'),
    ('Kitchen Knife Set', 'Home & Garden', 79.99, datetime('now', '-3 days'), datetime('now', '-1 days'), 'active'),
    ('Magazine', 'Books', 9.99, datetime('now', '-1 days'), datetime('now', '-1 days'), 'active');

-- Insert sample sessions (200 sessions)
INSERT INTO sessions (user_id, session_token, created_at, updated_at, ip_address, user_agent, duration_seconds, pages_visited, device_type, browser)
SELECT 
    (abs(random()) % 100) + 1,
    'session_' || (row_number() OVER ()) || '_' || strftime('%s', 'now'),
    datetime('now', '-' || (abs(random()) % 90) || ' days'),
    datetime('now', '-' || (abs(random()) % 90) || ' days', '+' || (abs(random()) % 7200) || ' seconds'),
    '192.168.' || (abs(random()) % 255) || '.' || (abs(random()) % 255),
    CASE 
        WHEN abs(random()) % 10 > 6 THEN 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        WHEN abs(random()) % 10 > 3 THEN 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
        ELSE 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36'
    END,
    (abs(random()) % 3600) + 30,
    (abs(random()) % 20) + 1,
    CASE 
        WHEN abs(random()) % 10 > 7 THEN 'desktop'
        WHEN abs(random()) % 10 > 4 THEN 'mobile'
        ELSE 'tablet'
    END,
    CASE 
        WHEN abs(random()) % 10 > 5 THEN 'Chrome'
        WHEN abs(random()) % 10 > 3 THEN 'Firefox'
        WHEN abs(random()) % 10 > 1 THEN 'Safari'
        ELSE 'Edge'
    END
FROM (
    SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
    SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
    SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
    SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
    SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
    SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
    SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
    SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION
    SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION
    SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION
    SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION
    SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION
    SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION
    SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90 UNION
    SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95 UNION
    SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100 UNION
    SELECT 101 UNION SELECT 102 UNION SELECT 103 UNION SELECT 104 UNION SELECT 105 UNION
    SELECT 106 UNION SELECT 107 UNION SELECT 108 UNION SELECT 109 UNION SELECT 110 UNION
    SELECT 111 UNION SELECT 112 UNION SELECT 113 UNION SELECT 114 UNION SELECT 115 UNION
    SELECT 116 UNION SELECT 117 UNION SELECT 118 UNION SELECT 119 UNION SELECT 120 UNION
    SELECT 121 UNION SELECT 122 UNION SELECT 123 UNION SELECT 124 UNION SELECT 125 UNION
    SELECT 126 UNION SELECT 127 UNION SELECT 128 UNION SELECT 129 UNION SELECT 130 UNION
    SELECT 131 UNION SELECT 132 UNION SELECT 133 UNION SELECT 134 UNION SELECT 135 UNION
    SELECT 136 UNION SELECT 137 UNION SELECT 138 UNION SELECT 139 UNION SELECT 140 UNION
    SELECT 141 UNION SELECT 142 UNION SELECT 143 UNION SELECT 144 UNION SELECT 145 UNION
    SELECT 146 UNION SELECT 147 UNION SELECT 148 UNION SELECT 149 UNION SELECT 150 UNION
    SELECT 151 UNION SELECT 152 UNION SELECT 153 UNION SELECT 154 UNION SELECT 155 UNION
    SELECT 156 UNION SELECT 157 UNION SELECT 158 UNION SELECT 159 UNION SELECT 160 UNION
    SELECT 161 UNION SELECT 162 UNION SELECT 163 UNION SELECT 164 UNION SELECT 165 UNION
    SELECT 166 UNION SELECT 167 UNION SELECT 168 UNION SELECT 169 UNION SELECT 170 UNION
    SELECT 171 UNION SELECT 172 UNION SELECT 173 UNION SELECT 174 UNION SELECT 175 UNION
    SELECT 176 UNION SELECT 177 UNION SELECT 178 UNION SELECT 179 UNION SELECT 180 UNION
    SELECT 181 UNION SELECT 182 UNION SELECT 183 UNION SELECT 184 UNION SELECT 185 UNION
    SELECT 186 UNION SELECT 187 UNION SELECT 188 UNION SELECT 189 UNION SELECT 190 UNION
    SELECT 191 UNION SELECT 192 UNION SELECT 193 UNION SELECT 194 UNION SELECT 195 UNION
    SELECT 196 UNION SELECT 197 UNION SELECT 198 UNION SELECT 199 UNION SELECT 200
);

-- Insert sample events (500 events)
INSERT INTO events (user_id, session_id, event_type, event_data, created_at, page_url, referrer)
SELECT 
    (abs(random()) % 100) + 1,
    (abs(random()) % 200) + 1,
    CASE 
        WHEN abs(random()) % 10 > 7 THEN 'page_view'
        WHEN abs(random()) % 10 > 5 THEN 'click'
        WHEN abs(random()) % 10 > 3 THEN 'form_submit'
        WHEN abs(random()) % 10 > 1 THEN 'purchase'
        ELSE 'logout'
    END,
    json_object(
        'timestamp', datetime('now', '-' || (abs(random()) % 90) || ' days'),
        'value', abs(random()) % 100,
        'category', CASE 
            WHEN abs(random()) % 10 > 5 THEN 'engagement'
            ELSE 'conversion'
        END
    ),
    datetime('now', '-' || (abs(random()) % 90) || ' days'),
    '/page/' || (abs(random()) % 50) + 1,
    CASE 
        WHEN abs(random()) % 10 > 5 THEN 'https://google.com'
        WHEN abs(random()) % 10 > 3 THEN 'https://facebook.com'
        WHEN abs(random()) % 10 > 1 THEN 'https://twitter.com'
        ELSE NULL
    END
FROM (
    SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
    SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
    SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
    SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
    SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
    SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
    SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
    SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION
    SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION
    SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION
    SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION
    SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION
    SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION
    SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90 UNION
    SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95 UNION
    SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100 UNION
    SELECT 101 UNION SELECT 102 UNION SELECT 103 UNION SELECT 104 UNION SELECT 105 UNION
    SELECT 106 UNION SELECT 107 UNION SELECT 108 UNION SELECT 109 UNION SELECT 110 UNION
    SELECT 111 UNION SELECT 112 UNION SELECT 113 UNION SELECT 114 UNION SELECT 115 UNION
    SELECT 116 UNION SELECT 117 UNION SELECT 118 UNION SELECT 119 UNION SELECT 120 UNION
    SELECT 121 UNION SELECT 122 UNION SELECT 123 UNION SELECT 124 UNION SELECT 125 UNION
    SELECT 126 UNION SELECT 127 UNION SELECT 128 UNION SELECT 129 UNION SELECT 130 UNION
    SELECT 131 UNION SELECT 132 UNION SELECT 133 UNION SELECT 134 UNION SELECT 135 UNION
    SELECT 136 UNION SELECT 137 UNION SELECT 138 UNION SELECT 139 UNION SELECT 140 UNION
    SELECT 141 UNION SELECT 142 UNION SELECT 143 UNION SELECT 144 UNION SELECT 145 UNION
    SELECT 146 UNION SELECT 147 UNION SELECT 148 UNION SELECT 149 UNION SELECT 150 UNION
    SELECT 151 UNION SELECT 152 UNION SELECT 153 UNION SELECT 154 UNION SELECT 155 UNION
    SELECT 156 UNION SELECT 157 UNION SELECT 158 UNION SELECT 159 UNION SELECT 160 UNION
    SELECT 161 UNION SELECT 162 UNION SELECT 163 UNION SELECT 164 UNION SELECT 165 UNION
    SELECT 166 UNION SELECT 167 UNION SELECT 168 UNION SELECT 169 UNION SELECT 170 UNION
    SELECT 171 UNION SELECT 172 UNION SELECT 173 UNION SELECT 174 UNION SELECT 175 UNION
    SELECT 176 UNION SELECT 177 UNION SELECT 178 UNION SELECT 179 UNION SELECT 180 UNION
    SELECT 181 UNION SELECT 182 UNION SELECT 183 UNION SELECT 184 UNION SELECT 185 UNION
    SELECT 186 UNION SELECT 187 UNION SELECT 188 UNION SELECT 189 UNION SELECT 190 UNION
    SELECT 191 UNION SELECT 192 UNION SELECT 193 UNION SELECT 194 UNION SELECT 195 UNION
    SELECT 196 UNION SELECT 197 UNION SELECT 198 UNION SELECT 199 UNION SELECT 200 UNION
    SELECT 201 UNION SELECT 202 UNION SELECT 203 UNION SELECT 204 UNION SELECT 205 UNION
    SELECT 206 UNION SELECT 207 UNION SELECT 208 UNION SELECT 209 UNION SELECT 210 UNION
    SELECT 211 UNION SELECT 212 UNION SELECT 213 UNION SELECT 214 UNION SELECT 215 UNION
    SELECT 216 UNION SELECT 217 UNION SELECT 218 UNION SELECT 219 UNION SELECT 220 UNION
    SELECT 221 UNION SELECT 222 UNION SELECT 223 UNION SELECT 224 UNION SELECT 225 UNION
    SELECT 226 UNION SELECT 227 UNION SELECT 228 UNION SELECT 229 UNION SELECT 230 UNION
    SELECT 231 UNION SELECT 232 UNION SELECT 233 UNION SELECT 234 UNION SELECT 235 UNION
    SELECT 236 UNION SELECT 237 UNION SELECT 238 UNION SELECT 239 UNION SELECT 240 UNION
    SELECT 241 UNION SELECT 242 UNION SELECT 243 UNION SELECT 244 UNION SELECT 245 UNION
    SELECT 246 UNION SELECT 247 UNION SELECT 248 UNION SELECT 249 UNION SELECT 250 UNION
    SELECT 251 UNION SELECT 252 UNION SELECT 253 UNION SELECT 254 UNION SELECT 255 UNION
    SELECT 256 UNION SELECT 257 UNION SELECT 258 UNION SELECT 259 UNION SELECT 260 UNION
    SELECT 261 UNION SELECT 262 UNION SELECT 263 UNION SELECT 264 UNION SELECT 265 UNION
    SELECT 266 UNION SELECT 267 UNION SELECT 268 UNION SELECT 269 UNION SELECT 270 UNION
    SELECT 271 UNION SELECT 272 UNION SELECT 273 UNION SELECT 274 UNION SELECT 275 UNION
    SELECT 276 UNION SELECT 277 UNION SELECT 278 UNION SELECT 279 UNION SELECT 280 UNION
    SELECT 281 UNION SELECT 282 UNION SELECT 283 UNION SELECT 284 UNION SELECT 285 UNION
    SELECT 286 UNION SELECT 287 UNION SELECT 288 UNION SELECT 289 UNION SELECT 290 UNION
    SELECT 291 UNION SELECT 292 UNION SELECT 293 UNION SELECT 294 UNION SELECT 295 UNION
    SELECT 296 UNION SELECT 297 UNION SELECT 298 UNION SELECT 299 UNION SELECT 300 UNION
    SELECT 301 UNION SELECT 302 UNION SELECT 303 UNION SELECT 304 UNION SELECT 305 UNION
    SELECT 306 UNION SELECT 307 UNION SELECT 308 UNION SELECT 309 UNION SELECT 310 UNION
    SELECT 311 UNION SELECT 312 UNION SELECT 313 UNION SELECT 314 UNION SELECT 315 UNION
    SELECT 316 UNION SELECT 317 UNION SELECT 318 UNION SELECT 319 UNION SELECT 320 UNION
    SELECT 321 UNION SELECT 322 UNION SELECT 323 UNION SELECT 324 UNION SELECT 325 UNION
    SELECT 326 UNION SELECT 327 UNION SELECT 328 UNION SELECT 329 UNION SELECT 330 UNION
    SELECT 331 UNION SELECT 332 UNION SELECT 333 UNION SELECT 334 UNION SELECT 335 UNION
    SELECT 336 UNION SELECT 337 UNION SELECT 338 UNION SELECT 339 UNION SELECT 340 UNION
    SELECT 341 UNION SELECT 342 UNION SELECT 343 UNION SELECT 344 UNION SELECT 345 UNION
    SELECT 346 UNION SELECT 347 UNION SELECT 348 UNION SELECT 349 UNION SELECT 350 UNION
    SELECT 351 UNION SELECT 352 UNION SELECT 353 UNION SELECT 354 UNION SELECT 355 UNION
    SELECT 356 UNION SELECT 357 UNION SELECT 358 UNION SELECT 359 UNION SELECT 360 UNION
    SELECT 361 UNION SELECT 362 UNION SELECT 363 UNION SELECT 364 UNION SELECT 365 UNION
    SELECT 366 UNION SELECT 367 UNION SELECT 368 UNION SELECT 369 UNION SELECT 370 UNION
    SELECT 371 UNION SELECT 372 UNION SELECT 373 UNION SELECT 374 UNION SELECT 375 UNION
    SELECT 376 UNION SELECT 377 UNION SELECT 378 UNION SELECT 379 UNION SELECT 380 UNION
    SELECT 381 UNION SELECT 382 UNION SELECT 383 UNION SELECT 384 UNION SELECT 385 UNION
    SELECT 386 UNION SELECT 387 UNION SELECT 388 UNION SELECT 389 UNION SELECT 390 UNION
    SELECT 391 UNION SELECT 392 UNION SELECT 393 UNION SELECT 394 UNION SELECT 395 UNION
    SELECT 396 UNION SELECT 397 UNION SELECT 398 UNION SELECT 399 UNION SELECT 400 UNION
    SELECT 401 UNION SELECT 402 UNION SELECT 403 UNION SELECT 404 UNION SELECT 405 UNION
    SELECT 406 UNION SELECT 407 UNION SELECT 408 UNION SELECT 409 UNION SELECT 410 UNION
    SELECT 411 UNION SELECT 412 UNION SELECT 413 UNION SELECT 414 UNION SELECT 415 UNION
    SELECT 416 UNION SELECT 417 UNION SELECT 418 UNION SELECT 419 UNION SELECT 420 UNION
    SELECT 421 UNION SELECT 422 UNION SELECT 423 UNION SELECT 424 UNION SELECT 425 UNION
    SELECT 426 UNION SELECT 427 UNION SELECT 428 UNION SELECT 429 UNION SELECT 430 UNION
    SELECT 431 UNION SELECT 432 UNION SELECT 433 UNION SELECT 434 UNION SELECT 435 UNION
    SELECT 436 UNION SELECT 437 UNION SELECT 438 UNION SELECT 439 UNION SELECT 440 UNION
    SELECT 441 UNION SELECT 442 UNION SELECT 443 UNION SELECT 444 UNION SELECT 445 UNION
    SELECT 446 UNION SELECT 447 UNION SELECT 448 UNION SELECT 449 UNION SELECT 450 UNION
    SELECT 451 UNION SELECT 452 UNION SELECT 453 UNION SELECT 454 UNION SELECT 455 UNION
    SELECT 456 UNION SELECT 457 UNION SELECT 458 UNION SELECT 459 UNION SELECT 460 UNION
    SELECT 461 UNION SELECT 462 UNION SELECT 463 UNION SELECT 464 UNION SELECT 465 UNION
    SELECT 466 UNION SELECT 467 UNION SELECT 468 UNION SELECT 469 UNION SELECT 470 UNION
    SELECT 471 UNION SELECT 472 UNION SELECT 473 UNION SELECT 474 UNION SELECT 475 UNION
    SELECT 476 UNION SELECT 477 UNION SELECT 478 UNION SELECT 479 UNION SELECT 480 UNION
    SELECT 481 UNION SELECT 482 UNION SELECT 483 UNION SELECT 484 UNION SELECT 485 UNION
    SELECT 486 UNION SELECT 487 UNION SELECT 488 UNION SELECT 489 UNION SELECT 490 UNION
    SELECT 491 UNION SELECT 492 UNION SELECT 493 UNION SELECT 494 UNION SELECT 495 UNION
    SELECT 496 UNION SELECT 497 UNION SELECT 498 UNION SELECT 499 UNION SELECT 500
);

-- Insert sample orders (100 orders)
INSERT INTO orders (user_id, product_id, quantity, total_amount, status, created_at, updated_at)
SELECT 
    (abs(random()) % 100) + 1,
    (abs(random()) % 20) + 1,
    (abs(random()) % 5) + 1,
    (abs(random()) % 1000) + 10.0,
    CASE 
        WHEN abs(random()) % 10 > 8 THEN 'completed'
        WHEN abs(random()) % 10 > 6 THEN 'shipped'
        WHEN abs(random()) % 10 > 4 THEN 'processing'
        WHEN abs(random()) % 10 > 2 THEN 'pending'
        ELSE 'cancelled'
    END,
    datetime('now', '-' || (abs(random()) % 180) || ' days'),
    datetime('now', '-' || (abs(random()) % 180) || ' days', '+' || (abs(random()) % 7) || ' days')
FROM (
    SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
    SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION
    SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION
    SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION
    SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION
    SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION
    SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION
    SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55 UNION
    SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60 UNION
    SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65 UNION
    SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70 UNION
    SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75 UNION
    SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80 UNION
    SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85 UNION
    SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90 UNION
    SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95 UNION
    SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);
CREATE INDEX IF NOT EXISTS idx_users_last_login ON users(last_login);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_created_at ON sessions(created_at);
CREATE INDEX IF NOT EXISTS idx_events_user_id ON events(user_id);
CREATE INDEX IF NOT EXISTS idx_events_session_id ON events(session_id);
CREATE INDEX IF NOT EXISTS idx_events_event_type ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

-- Create some useful views for analytics
CREATE VIEW IF NOT EXISTS user_activity_summary AS
SELECT 
    u.id,
    u.name,
    u.email,
    u.created_at as user_created_at,
    u.last_login,
    u.subscription_plan,
    COUNT(DISTINCT s.id) as total_sessions,
    COUNT(DISTINCT e.id) as total_events,
    COUNT(DISTINCT o.id) as total_orders,
    COALESCE(SUM(o.total_amount), 0) as total_spent
FROM users u
LEFT JOIN sessions s ON u.id = s.user_id
LEFT JOIN events e ON u.id = e.user_id
LEFT JOIN orders o ON u.id = o.user_id
GROUP BY u.id, u.name, u.email, u.created_at, u.last_login, u.subscription_plan;

CREATE VIEW IF NOT EXISTS daily_metrics AS
SELECT 
    date(created_at) as date,
    COUNT(*) as daily_users,
    COUNT(CASE WHEN last_login >= date(created_at) THEN 1 END) as active_users,
    COUNT(CASE WHEN subscription_plan != 'free' THEN 1 END) as paid_users
FROM users
WHERE created_at >= datetime('now', '-90 days')
GROUP BY date(created_at)
ORDER BY date DESC;

-- Insert some recent activity for testing
INSERT INTO users (name, email, created_at, updated_at, last_login, status, user_type, country, age, subscription_plan)
VALUES 
    ('Recent User 1', 'recent1@example.com', datetime('now', '-1 day'), datetime('now'), datetime('now', '-1 hour'), 'active', 'premium', 'USA', 25, 'premium'),
    ('Recent User 2', 'recent2@example.com', datetime('now', '-2 days'), datetime('now'), datetime('now', '-2 hours'), 'active', 'pro', 'Canada', 30, 'basic'),
    ('Recent User 3', 'recent3@example.com', datetime('now', '-3 days'), datetime('now'), datetime('now', '-3 hours'), 'active', 'regular', 'UK', 28, 'free');

-- Add some recent sessions for the new users
INSERT INTO sessions (user_id, session_token, created_at, updated_at, duration_seconds, pages_visited, device_type, browser)
SELECT 
    u.id,
    'recent_session_' || u.id || '_' || strftime('%s', 'now'),
    datetime('now', '-1 hour'),
    datetime('now'),
    (abs(random()) % 1800) + 300,
    (abs(random()) % 10) + 1,
    'desktop',
    'Chrome'
FROM users u 
WHERE u.email LIKE 'recent%@example.com';

-- Display summary statistics
SELECT 'Database seeded successfully!' as message;
SELECT 'Users: ' || COUNT(*) as users_count FROM users;
SELECT 'Sessions: ' || COUNT(*) as sessions_count FROM sessions;
SELECT 'Events: ' || COUNT(*) as events_count FROM events;
SELECT 'Products: ' || COUNT(*) as products_count FROM products;
SELECT 'Orders: ' || COUNT(*) as orders_count FROM orders;